apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cs3219
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: cs3219/order-service:1.0.0
