apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
