apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
